version: '3.5'
services:
    backend:
        image: popdriver-backend
        ports:
            - "80:80"
    database:
        image: popdriver-db
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: popdriver
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
        volumes:
            db-volume:/var/lib/mysql
volumes:
    db-volume: